/* Copyright 2019 Schibsted */

/***
 *
 * Can parse:
 * Assorted university journals with red top bar
 *
 */
module.exports = {
  /***
   * The parse method for "university" will extract data from the raw text generated by DocumentCloud
   * for a PDF.
   * To determine if the parser was able to parse the file, check the returnValue.parsed field
   * (true|false).
   */
  parse: function(raw) {
    var topDown = require('./topDownParser');

    var rawA = raw.split('Dok.:');
    // console.log("antall: " + (rawA.length-1));

    var items = [];
    var globalParsed = false;

    // var result = topDown.parse(raw, this.options);
    // loop all parts like sagene - skip first element
    for (var cases = 1; cases < rawA.length; cases++) {
      try {
        var result = topDown.parse(rawA[cases], this.options);
        if (result.parsed) {
          var item = result.items[0];

          // move to function
          //split caseOfficer on / to give department and person as separate fields
          item.caseResponsible = '';

          if (item.caseOfficer.indexOf('/') > 0) {
            var caseParts = item.caseOfficer.split('/');
            item.caseResponsible = caseParts[0].trim();
            item.caseOfficer = caseParts[1].trim();
          }

          // move to function
          // some sources prefix title with I, or U, - but need to handle N & X screened as well
          item.receiver = item.sender = '';

          if (item.senderOrReceiverLabel == 'Mottaker:') {
            item.receiver = item.senderOrReceiver;
            item.documentType = 'U';
          } else {
            item.sender = item.senderOrReceiver;
            item.documentType = 'I';
          }

          //adjust date format to date format
          item.documentDate = getDateFromString(item.documentDate);
          item.recordedDate = getDateFromString(item.recordedDate);

          items.push(item);
          globalParsed = true;
        } else {
          console.log(cases);
          // if(cases == 1 ) console.log(rawA[cases]);
        }
      } catch (e) {}
    }

    if (globalParsed) {
      return {
        parsed: true,
        items: items,
      };
    }

    return {
      parsed: false,
      items: items,
      error: { message: 'No items found in source' },
    };

    /***
     * Converts a string with the format "dd.mm.yyyy" to a date object.
     * todo: move generic function inside topDown? call with format style
     */
    function getDateFromString(dateString) {
      try {
        if (dateString.length === 10) {
          var dateParts = dateString.split('.');
          var year = dateParts[2];
          var month = dateParts[1];
          var day = dateParts[0];
        } else {
          return '';
        }
        /*
         Parse the date as a string to avoid one day offset
         http://stackoverflow.com/questions/7556591/javascript-date-object-always-one-day-off)
         */
        return new Date('"' + year + '/' + month + '/' + day + '"');
      } catch (e) {
        return '';
      }
    }
  },

  options: {
    fields: [
      {
        name: 'caseNumber',
        regexList: [/(\d{2,4}\/\d{3,6}-\d{1,4})/],
      },
      {
        name: 'documentTitle',
        regexList: [/Dok.:([\s\S]*?)Sak:/, /([\s\S]*?)Sak:/],
      },
      {
        name: 'caseTitle',
        regexList: [/Sak:([\s\S]*?)(Mottaker|Avsender):/],
      },
      {
        name: 'senderOrReceiver',
        regexList: [/(?:Mottaker:|Avsender:)([\s\S]*?)Journaldato:/],
      },
      {
        name: 'senderOrReceiverLabel',
        regexList: [/(Mottaker:|Avsender:)/],
      },
      {
        name: 'documentDate',
        regexList: [/Dok. dato:([\s\S]*?)Arkivdel:/],
      },
      {
        name: 'recordedDate',
        regexList: [/Journaldato:([\s\S]*?)Tilg. kode:/],
      },
      {
        name: 'caseOfficer',
        regexList: [/Saksbehandler:([\s\S]*?)Dok./],
      },
      {
        name: 'classification',
        regexList: [
          /Klasse:([\s\S]*?)Avskrevet:/,
          /Arkivkode:([\s\S]*?)Avskrevet:/,
        ],
      },
      {
        name: 'legalParagraph',
        regexList: [/Tilg. kode:([\s\S]*?)Saksbehandler:/],
      },
    ],

    noise: [],
  },
};
