exports.seed = function(knex, Promise) {
  return knex
    .raw('TRUNCATE TABLE country, project, list, source CASCADE')
    .then(() =>
      knex('country')
        .insert([
          { id: 1, name: 'Norge', country_code: 'NO' },
          { id: 2, name: 'Danmark', country_code: 'DK' },
        ])
        .then(() =>
          knex('project').insert([
            {
              id: 12,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-11-18',
              source_regex:
                '(HSO|hso|SSHF|sshf|SOHF|AHUS|SUN|SIV|SIN|VVHF|SPHF|FIHF|HMR|HVE|HMN|HNO|STHF|HFHF|HNT|HSHF|NLSH|UNN|HBHF|SUS|HFOE|STO|OUS)',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 13,
              name: 'Mattilsynet',
              description: '',
              registered_date: '2017-11-01',
              source_regex: '',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 14,
              name: 'Kommuner',
              description: '',
              registered_date: '2017-12-19',
              source_regex: '(BER)',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 3,
              name: 'Stortinget',
              description: '',
              registered_date: '2016-09-09',
              source_regex: '(Sto)',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 6,
              name: 'Politiet',
              description: '',
              registered_date: '2016-09-09',
              source_regex: '(pdid{2})|(PDId{2})',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 2,
              name: 'Universitetene',
              description: '',
              registered_date: '2016-09-09',
              source_regex: '^d*-(.{4})[ -]|^d*-(.{3})[d -]',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 5,
              name: 'Forsvaret',
              description: '',
              registered_date: '2016-09-09',
              source_regex:
                '(BRIG-N|LDKN|LST|HST|FOH|CYFOR|BRIGN|HVST|FMA|FLO|FMS|FSAN|FSA|FST|FS|KV|LSK|SST)',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 4,
              name: 'Den Norske Kirke',
              description: '',
              registered_date: '2016-09-09',
              source_regex: '-(KR)-|-(Kr)-',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 7,
              name: 'Oslo Kommune',
              description: '',
              registered_date: '2016-09-09',
              source_regex: '([a-zA-Z]{3,4})d',
              is_visible: 't',
              country_id: 1,
            },
            {
              id: 15,
              name: 'Fylkeskommuner',
              description: '',
              registered_date: '2018-02-14',
              source_regex: '(Off)',
              is_visible: 't',
              country_id: 1,
            },
          ]),
        )
        .then(() =>
          knex('list').insert([
            {
              id: 1,
              name: 'Etater',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 2,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 3,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 4,
              name: 'Foretak',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 5,
              name: 'Foretak',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 6,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 7,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 8,
              name: 'Etater',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 9,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 10,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 11,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-08-31',
            },
            {
              id: 12,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 13,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 14,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 15,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 16,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 17,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 18,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 19,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 20,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 21,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 22,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 23,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 24,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 25,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 26,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 27,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 28,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 29,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 30,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 31,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 32,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 33,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-08',
            },
            {
              id: 34,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 35,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 36,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 37,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 38,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 39,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 40,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 41,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 42,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 43,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 44,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 45,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 46,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 47,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 48,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 49,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 50,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 51,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 52,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 53,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 54,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 55,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 56,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 57,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 58,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 59,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 60,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 61,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 62,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 63,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 64,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 65,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 66,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 67,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 68,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 69,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 70,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 71,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 72,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 73,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 74,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 75,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 76,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 77,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 78,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 79,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 80,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 81,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 82,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 83,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 84,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 85,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 86,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 87,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 88,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 89,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 90,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 91,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 92,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 93,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 94,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 95,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 96,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 97,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 98,
              name: 'Regionale Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 99,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 100,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 101,
              name: 'Universiteter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 102,
              name: 'Stortingsgrupper',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 103,
              name: 'Foretak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 105,
              name: 'Politidistrikt',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 106,
              name: 'Bydeler',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 107,
              name: 'Etater',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 108,
              name: 'Helseforetak',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 110,
              name: 'Kristiansand Havn',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 104,
              name: 'enheter',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 109,
              name: '',
              description: '',
              registered_date: '2016-09-09',
            },
            {
              id: 111,
              name: 'enhet',
              description: '',
              registered_date: '2017-11-06',
            },
            {
              id: 112,
              name: 'fylker',
              description: '',
              registered_date: '2018-02-14',
            },
          ]),
        )
        .then(() =>
          knex('source').insert([
            {
              id: 45,
              project_id: 7,
              list_id: 106,
              source_system: 'BAL',
              parser_name: 'BydelBjerke',
              name: 'Bydel Alna',
              email: 'postmottak@bal.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 46,
              project_id: 7,
              list_id: 106,
              source_system: 'BBJ',
              parser_name: 'BydelBjerke',
              name: 'Bydel Bjerke',
              email: 'bbj-postmottak@bbj.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 47,
              project_id: 7,
              list_id: 106,
              source_system: 'BFR',
              parser_name: 'BydelSagene',
              name: 'Bydel Frogner',
              email: 'postmottak@bfr.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 48,
              project_id: 7,
              list_id: 106,
              source_system: 'BGO',
              parser_name: 'BydelSagene',
              name: 'Bydel Gamle Oslo',
              email: 'postmottak@bgo.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 49,
              project_id: 7,
              list_id: 106,
              source_system: 'BGR',
              parser_name: 'BydelBjerke',
              name: 'Bydel Grorud',
              email: 'postmottak@bgr.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 50,
              project_id: 7,
              list_id: 106,
              source_system: 'BGA',
              parser_name: 'BydelBjerke',
              name: 'Bydel Grünerløkka',
              email: 'postmottak@bga.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 51,
              project_id: 7,
              list_id: 106,
              source_system: 'BNA',
              parser_name: 'BydelBjerke',
              name: 'Bydel Nordre Aker',
              email: 'postmottak@bna.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 53,
              project_id: 7,
              list_id: 106,
              source_system: 'BSA',
              parser_name: 'BydelSagene',
              name: 'Bydel Sagene',
              email: 'postmottak@bsa.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 54,
              project_id: 7,
              list_id: 106,
              source_system: 'BSH',
              parser_name: 'BydelBjerke',
              name: 'Bydel St. Hanshaugen',
              email: 'postmottak@bsh.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 55,
              project_id: 7,
              list_id: 106,
              source_system: 'BSR',
              parser_name: 'BydelBjerke',
              name: 'Bydel Stovner',
              email: 'postmottak@bsr.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 57,
              project_id: 7,
              list_id: 106,
              source_system: 'BUN',
              parser_name: 'BydelSagene',
              name: 'Bydel Ullern',
              email: 'postmottak@bun.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 14,
              project_id: 2,
              list_id: 101,
              source_system: 'NMBU',
              parser_name: 'MicrosoftReportingServices',
              name: 'NMBU',
              email: 'post@nmbu.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 59,
              project_id: 7,
              list_id: 106,
              source_system: 'BOS',
              parser_name: 'BydelBjerke',
              name: 'Bydel Østensjø',
              email: 'postmottak@bos.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 60,
              project_id: 7,
              list_id: 107,
              source_system: 'BFE',
              parser_name: 'Renovasjonsetaten',
              name: 'Barne- og familieetaten',
              email: 'postmottak@bfe.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 63,
              project_id: 7,
              list_id: 107,
              source_system: 'BYA',
              parser_name: 'MunchMuseet',
              name: 'Byantikvaren',
              email: 'postmottak@bya.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 67,
              project_id: 7,
              list_id: 107,
              source_system: 'EGE',
              parser_name: 'Renovasjonsetaten',
              name: 'Energigjenvinningsetaten',
              email: 'postmottak@ege.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 70,
              project_id: 7,
              list_id: 107,
              source_system: 'HEL',
              parser_name: 'MunchMuseet',
              name: 'Helseetaten',
              email: 'postmottak@hel.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 64,
              project_id: 7,
              list_id: 107,
              source_system: 'BYM',
              parser_name: 'Naeringsetaten',
              name: 'Bymiljøetaten',
              email: 'postmottak@bym.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 69,
              project_id: 7,
              list_id: 107,
              source_system: 'GFE',
              parser_name: 'BydelSagene',
              name: 'Gravferdsetaten',
              email: 'postmottak@gfe.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 62,
              project_id: 7,
              list_id: 107,
              source_system: 'BRE',
              parser_name: 'Kemner',
              name: 'Brann- og redningsetaten',
              email: 'postmottak@bre.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 68,
              project_id: 7,
              list_id: 107,
              source_system: 'EMI',
              parser_name: 'BydelBjerke',
              name: 'Enhet for mangfold og integrering',
              email: 'emi@bga.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 158,
              project_id: 15,
              list_id: 112,
              source_system: 'FinnmarkFylke',
              parser_name: '',
              name: 'Finnmark',
              email: 'postmottak@ffk.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: true,
            },
            {
              id: 75,
              project_id: 7,
              list_id: 107,
              source_system: 'KRV',
              parser_name: 'Renovasjonsetaten',
              name: 'Kommunerevisjonen',
              email: 'postmottak@krv.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 76,
              project_id: 7,
              list_id: 107,
              source_system: 'KUL',
              parser_name: 'BydelBjerke',
              name: 'Kulturetaten',
              email: 'postmottak@kul.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 77,
              project_id: 7,
              list_id: 107,
              source_system: 'MUM',
              parser_name: 'MunchMuseet',
              name: 'Munchmuseet',
              email: 'postmottak@munchmuseet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 80,
              project_id: 7,
              list_id: 107,
              source_system: 'REN',
              parser_name: 'Renovasjonsetaten',
              name: 'Renovasjonsetaten',
              email: 'postmottak@ren.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 84,
              project_id: 7,
              list_id: 107,
              source_system: 'UDE',
              parser_name: 'Utdanningsetaten',
              name: 'Utdanningsetaten',
              email: 'postmottak@ude.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 87,
              project_id: 7,
              list_id: 107,
              source_system: 'VEL',
              parser_name: 'Velferdsetaten',
              name: 'Velferdsetaten',
              email: 'postmottak@vel.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 88,
              project_id: 7,
              list_id: 107,
              source_system: 'UBF',
              parser_name: 'Undervisningsbygg',
              name: 'Undervisningsbygg',
              email: 'postmottak@ubf.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 89,
              project_id: 7,
              list_id: 107,
              source_system: 'OBY',
              parser_name: 'Renovasjonsetaten',
              name: 'Omsorgsbygg',
              email: 'postmottak@oby.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 90,
              project_id: 7,
              list_id: 107,
              source_system: 'BBY',
              parser_name: 'BydelBjerke',
              name: 'Boligbygg',
              email: 'postmottak@bby.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 92,
              project_id: 7,
              list_id: 107,
              source_system: 'HAV',
              parser_name: 'BydelSagene',
              name: 'Oslo Havn KF',
              email: 'postmottak@hav.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 15,
              project_id: 3,
              list_id: 102,
              source_system: 'STO',
              parser_name: 'BydelSagene',
              name: 'Stortinget',
              email: 'postmottak@stortinget.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 52,
              project_id: 7,
              list_id: 106,
              source_system: 'BNS',
              parser_name: 'BydelBjerke',
              name: 'Bydel Nordstrand',
              email: 'postmottak@bns.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 56,
              project_id: 7,
              list_id: 106,
              source_system: 'BSN',
              parser_name: 'BydelSagene',
              name: 'Bydel Søndre Nordstrand ',
              email: 'postmottak@bsn.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 82,
              project_id: 7,
              list_id: 107,
              source_system: 'SYE',
              parser_name: 'BydelBjerke',
              name: 'Sykehjemsetaten',
              email: 'postmottak@sye.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 85,
              project_id: 7,
              list_id: 107,
              source_system: 'UKE',
              parser_name: 'BydelBjerke',
              name: 'Utviklings- og kompetanseetaten ',
              email: 'postmottak@uke.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 78,
              project_id: 7,
              list_id: 107,
              source_system: 'NAE',
              parser_name: 'Naeringsetaten',
              name: 'Næringsetaten',
              email: 'postmottak@nae.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 86,
              project_id: 7,
              list_id: 107,
              source_system: 'VAV',
              parser_name: 'Naeringsetaten',
              name: 'Vann- og avløpsetaten',
              email: 'postmottak@vav.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 97,
              project_id: 7,
              list_id: 107,
              source_system: 'RUT',
              parser_name: 'BydelSagene',
              name: 'Ruter AS',
              email: 'post@ruter.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 72,
              project_id: 7,
              list_id: 107,
              source_system: 'KEM',
              parser_name: 'Kemner',
              name: 'Kemnerkontoret ',
              email: 'postmottak@kem.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 95,
              project_id: 7,
              list_id: 107,
              source_system: 'SPO',
              parser_name: 'Renovasjonsetaten',
              name: 'Sporveien Oslo AS ',
              email: 'firmapost@sporveien.com',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 96,
              project_id: 7,
              list_id: 107,
              source_system: 'TRI',
              parser_name: 'Renovasjonsetaten',
              name: 'Sporveien Trikken AS ',
              email: 'trikken@sporveien.com',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 79,
              project_id: 7,
              list_id: 107,
              source_system: 'PBE',
              parser_name: 'PlanOgBygningsetaten',
              name: 'Plan- og bygningsetaten',
              email: 'postmottak@pbe.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 100,
              project_id: 7,
              list_id: 107,
              source_system: 'BYS',
              parser_name: 'Bystyret',
              name: 'Bystyrets sekretariat',
              email: 'postmottak@oslobystyre.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 101,
              project_id: 7,
              list_id: 107,
              source_system: 'BYR',
              parser_name: 'Byradet',
              name: 'Byrådsadministrasjonen',
              email: 'postmottak@byr.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 152,
              project_id: 15,
              list_id: 112,
              source_system: 'ØstfoldFylke',
              parser_name: '',
              name: 'Østfold',
              email: 'sentralpost@ostfoldfk.no',
              description: '',
              registered_date: '2018-02-14',
              is_visible: true,
            },
            {
              id: 153,
              project_id: 15,
              list_id: 112,
              source_system: 'HordalandFylke',
              parser_name: '',
              name: 'Hordaland',
              email: 'postmottak@hfk.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: true,
            },
            {
              id: 154,
              project_id: 15,
              list_id: 112,
              source_system: 'VestAgderFylke',
              parser_name: '',
              name: 'Vest-Agder',
              email: 'postmottak@vaf.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: true,
            },
            {
              id: 155,
              project_id: 15,
              list_id: 112,
              source_system: 'VestfoldFylke',
              parser_name: '',
              name: 'Vestfold',
              email: 'postmottak@vfk.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: true,
            },
            {
              id: 16,
              project_id: 4,
              list_id: 103,
              source_system: 'KR',
              parser_name: 'HSO',
              name: 'Kirkerådet',
              email: 'post.kirkeradet@kirken.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 159,
              project_id: 15,
              list_id: 112,
              source_system: 'TromsFylke',
              parser_name: 'Jupiter',
              name: 'Troms',
              email: 'postmottak@tromsfylke.no',
              description: '',
              registered_date: '2018-02-21',
              is_visible: true,
            },
            {
              id: 161,
              project_id: 15,
              list_id: 112,
              source_system: 'RogalandFylke',
              parser_name: 'Jupiter',
              name: 'Rogaland',
              email: 'firmapost@rogfk.no',
              description: '',
              registered_date: '2018-02-21',
              is_visible: true,
            },
            {
              id: 103,
              project_id: 12,
              list_id: 109,
              source_system: 'SSHF',
              parser_name: 'SSHF',
              name: 'Sørlandet Sykehus HF',
              email: 'postmottak@sshf.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 156,
              project_id: 15,
              list_id: 112,
              source_system: 'SørTrøndelagFylke',
              parser_name: '',
              name: 'Sør-Trøndelag',
              email: 'postmottak@stfk.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: false,
            },
            {
              id: 7,
              project_id: 2,
              list_id: 101,
              source_system: 'UIA_WEB',
              parser_name: 'StavangerKommune',
              name: 'UiA',
              email: 'post@uia.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 164,
              project_id: 15,
              list_id: 112,
              source_system: 'OpplandFylke',
              parser_name: 'StavangerKommune',
              name: 'Oppland',
              email: 'postmottak@oppland.org',
              description: '',
              registered_date: '2018-03-23',
              is_visible: true,
            },
            {
              id: 165,
              project_id: 15,
              list_id: 112,
              source_system: 'NordlandFylke',
              parser_name: 'HtmlParser',
              name: 'Nordland',
              email: 'post@nfk.no',
              description: '',
              registered_date: '2018-03-23',
              is_visible: true,
            },
            {
              id: 166,
              project_id: 15,
              list_id: 112,
              source_system: 'AustAgderFylke',
              parser_name: 'HtmlParser',
              name: 'Aust-Agder',
              email: 'postmottak@austagderfk.no',
              description: '',
              registered_date: '2018-04-03',
              is_visible: true,
            },
            {
              id: 167,
              project_id: 15,
              list_id: 112,
              source_system: 'BuskerudFylkeskommune',
              parser_name: 'HtmlParser',
              name: 'Buskerud',
              email: 'postmottak@bfk.no',
              description: '',
              registered_date: '2018-04-04',
              is_visible: true,
            },
            {
              id: 13,
              project_id: 2,
              list_id: 101,
              source_system: 'UIN',
              parser_name: 'MicrosoftReportingServices',
              name: 'Nord Universitet',
              email: 'postmottak@uin.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 11,
              project_id: 2,
              list_id: 101,
              source_system: 'UIS',
              parser_name: 'MicrosoftReportingServices',
              name: 'UiS',
              email: 'dokumentsenteret@uis.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 8,
              project_id: 2,
              list_id: 101,
              source_system: 'UIO',
              parser_name: 'GrapeCityActiveReports',
              name: 'UiO',
              email: 'ads-sfesd-post@admin.uio.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 18,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI01',
              parser_name: 'Velferdsetaten',
              name: 'Oslo politidistrikt',
              email: 'post.oslo@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 19,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI02',
              parser_name: 'Velferdsetaten',
              name: 'Øst politidistrikt',
              email: 'post.ost@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 9,
              project_id: 2,
              list_id: 101,
              source_system: 'UIB',
              parser_name: 'GrapeCityActiveReports',
              name: 'UiB',
              email: 'postmottak@uib.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 10,
              project_id: 2,
              list_id: 101,
              source_system: 'NTNU',
              parser_name: 'GrapeCityActiveReports',
              name: 'NTNU',
              email: 'postmottak@adm.ntnu.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 157,
              project_id: 15,
              list_id: 112,
              source_system: 'NordTrøndelagFylke',
              parser_name: '',
              name: 'Nord-Trøndelag',
              email: 'postmottak@ntfk.no',
              description: '',
              registered_date: '2018-02-15',
              is_visible: false,
            },
            {
              id: 12,
              project_id: 2,
              list_id: 101,
              source_system: 'UIT',
              parser_name: 'UiT',
              name: 'UiT',
              email: 'postmottak@uit.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 160,
              project_id: 15,
              list_id: 112,
              source_system: 'HedmarkFylke',
              parser_name: 'HedmarkFylkeskommune',
              name: 'Hedmark',
              email: 'postmottak@hedmark.org',
              description: '',
              registered_date: '2018-02-21',
              is_visible: true,
            },
            {
              id: 168,
              project_id: 15,
              list_id: 112,
              source_system: 'TelemarkFylke',
              parser_name: 'HtmlParser',
              name: 'Telemark',
              email: 'post@t-fk.no',
              description: '',
              registered_date: '2018-04-05',
              is_visible: true,
            },
            {
              id: 151,
              project_id: 14,
              list_id: null,
              source_system: 'BER',
              parser_name: 'HSO',
              name: 'Bergen kommune',
              email: 'postmottak@bergen.kommune.no',
              description: '',
              registered_date: '2017-12-19',
              is_visible: true,
            },
            {
              id: 66,
              project_id: 7,
              list_id: 107,
              source_system: 'EBY',
              parser_name: '',
              name: 'Eiendoms- og byfornyelsesetaten',
              email: 'postmottak@eby.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 58,
              project_id: 7,
              list_id: 106,
              source_system: 'BVA',
              parser_name: 'Renovasjonsetaten',
              name: 'Bydel Vestre Aker',
              email: 'postmottak@bva.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 169,
              project_id: 15,
              list_id: 112,
              source_system: 'SognOgFjordane',
              parser_name: 'HtmlParser',
              name: 'Sogn og Fjordane',
              email: 'post@sfj.no',
              description: '',
              registered_date: '2018-04-09',
              is_visible: true,
            },
            {
              id: 170,
              project_id: 15,
              list_id: 112,
              source_system: 'OFF',
              parser_name: 'OUS',
              name: 'Akershus',
              email: 'postmottak@afk.no',
              description: '',
              registered_date: '2018-04-11',
              is_visible: true,
            },
            {
              id: 143,
              project_id: 12,
              list_id: 109,
              source_system: 'OUS',
              parser_name: 'HSO',
              name: 'Oslo universitetssykehus HF',
              email: 'post@oslo-universitetssykehus.no',
              description: '',
              registered_date: '2017-10-09',
              is_visible: true,
            },
            {
              id: 162,
              project_id: 15,
              list_id: 112,
              source_system: 'MoreOgRomsdalFylke',
              parser_name: 'MoreOgRomsdalFylkeskommune',
              name: 'Møre og Romsdal',
              email: 'post@mrfylke.no',
              description: '',
              registered_date: '2018-02-21',
              is_visible: true,
            },
            {
              id: 108,
              project_id: 5,
              list_id: 104,
              source_system: 'FST',
              parser_name: 'Forsvaret',
              name: 'Forsvarsstaben',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 106,
              project_id: 5,
              list_id: 104,
              source_system: 'HST',
              parser_name: 'Forsvaret',
              name: 'Hærstaben',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 107,
              project_id: 5,
              list_id: 104,
              source_system: 'FOH',
              parser_name: 'Forsvaret',
              name: 'Fellesoperativt hovedkvarter',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 109,
              project_id: 5,
              list_id: 104,
              source_system: 'CYFOR',
              parser_name: 'Forsvaret',
              name: 'Cyberforsvaret',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 111,
              project_id: 5,
              list_id: 104,
              source_system: 'LST',
              parser_name: 'Forsvaret',
              name: 'Luftforsvarsstaben',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 112,
              project_id: 5,
              list_id: 104,
              source_system: 'HVST',
              parser_name: 'Forsvaret',
              name: 'Heimevernsstaben',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 114,
              project_id: 5,
              list_id: 104,
              source_system: 'FMA',
              parser_name: 'Forsvaret',
              name: 'Forsvarsmateriell',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 115,
              project_id: 5,
              list_id: 104,
              source_system: 'FLO',
              parser_name: 'Forsvaret',
              name: 'Forsvarets logistikkorganisasjon',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 116,
              project_id: 5,
              list_id: 104,
              source_system: 'FMS',
              parser_name: 'Forsvaret',
              name: 'Forsvarets mediesenter',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 117,
              project_id: 5,
              list_id: 104,
              source_system: 'FSA',
              parser_name: 'Forsvaret',
              name: 'Forsvarets sikkerhetsavdeling',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 118,
              project_id: 5,
              list_id: 104,
              source_system: 'FSAN',
              parser_name: 'Forsvaret',
              name: 'Forsvarets sanitet',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 119,
              project_id: 5,
              list_id: 104,
              source_system: 'KV',
              parser_name: 'Forsvaret',
              name: 'Kystvakten',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 120,
              project_id: 5,
              list_id: 104,
              source_system: 'LSK',
              parser_name: 'Forsvaret',
              name: 'Luftforsvarets skolesenter Kjevik',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 121,
              project_id: 5,
              list_id: 104,
              source_system: 'SST',
              parser_name: 'Forsvaret',
              name: 'Sjøforsvarsstaben',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 113,
              project_id: 5,
              list_id: 104,
              source_system: 'FS',
              parser_name: 'Forsvaret',
              name: 'Forsvarets spesialstyrker',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 122,
              project_id: 5,
              list_id: 104,
              source_system: 'LDKN',
              parser_name: 'Forsvaret',
              name: 'Landsdelskommando Nord-Norge',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 110,
              project_id: 5,
              list_id: 104,
              source_system: 'BRIG-N',
              parser_name: 'Forsvaret',
              name: 'Brigade Nord',
              email: 'forsvaret@mil.no',
              description: '',
              registered_date: '2016-11-16',
              is_visible: true,
            },
            {
              id: 61,
              project_id: 7,
              list_id: 107,
              source_system: 'BER',
              parser_name: '',
              name: 'Beredskapsetaten',
              email: 'postmottak@ber.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 73,
              project_id: 7,
              list_id: 107,
              source_system: 'ENE',
              parser_name: '',
              name: 'Klima- og energiprogrammet',
              email: 'postmottak@ene.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 74,
              project_id: 7,
              list_id: 107,
              source_system: 'KAO',
              parser_name: '',
              name: 'Kommuneadvokaten ',
              email: 'postmottak@kao.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 91,
              project_id: 7,
              list_id: 107,
              source_system: 'KID',
              parser_name: '',
              name: 'Kultur- og idrettsbygg Oslo KF',
              email: 'postmottak@kid.oslo.kommune.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 98,
              project_id: 7,
              list_id: 107,
              source_system: 'KON',
              parser_name: '',
              name: 'Oslo Konserthus AS',
              email: 'ok@oslokonserthus.no;',
              description: '',
              registered_date: '2016-09-09',
              is_visible: false,
            },
            {
              id: 102,
              project_id: 7,
              list_id: 107,
              source_system: 'TBA',
              parser_name: 'Bystyret',
              name: 'Sporveien T-bane AS',
              email: 't-banen@sporveien.com',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 172,
              project_id: 2,
              list_id: 101,
              source_system: 'USN',
              parser_name: 'MicrosoftReportingServices',
              name: 'USN',
              email: 'postmottak@usn.no',
              description: ' ',
              registered_date: '2018-09-19',
              is_visible: true,
            },
            {
              id: 148,
              project_id: 14,
              list_id: null,
              source_system: 'Kristiansand',
              parser_name: 'StavangerKommune',
              name: 'Kristiansand kommune',
              email: 'postmottak@kristiansand.kommune.no',
              description: '',
              registered_date: '2017-12-19',
              is_visible: true,
            },
            {
              id: 149,
              project_id: 14,
              list_id: null,
              source_system: 'Stavanger',
              parser_name: 'StavangerKommune',
              name: 'Stavanger kommune',
              email: 'innsyn@stavanger.kommune.no',
              description: '',
              registered_date: '2017-12-19',
              is_visible: true,
            },
            {
              id: 150,
              project_id: 14,
              list_id: null,
              source_system: 'Trondheim',
              parser_name: 'TrondheimKommune',
              name: 'Trondheim kommune',
              email: 'tk.postmottak@trondheim.kommune.no',
              description: '',
              registered_date: '2017-12-19',
              is_visible: true,
            },
            {
              id: 175,
              project_id: 15,
              list_id: 112,
              source_system: 'TrøndelagFylke',
              parser_name: 'Tieto',
              name: 'Trøndelag',
              email: 'postmottak@trondelagfylke.no',
              description: '',
              registered_date: '2019-05-26',
              is_visible: true,
            },
            {
              id: 20,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI03',
              parser_name: 'Velferdsetaten',
              name: 'Innlandet politidistrikt',
              email: 'post.innlandet@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 21,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI04',
              parser_name: 'Velferdsetaten',
              name: 'Sør-Øst politidistrikt',
              email: 'post.sor-ost@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 22,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI05',
              parser_name: 'Velferdsetaten',
              name: 'Agder politidistrikt',
              email: 'post.agder@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 23,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI06',
              parser_name: 'Velferdsetaten',
              name: 'Sør-Vest politidistrikt',
              email: 'post.sor-vest@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 24,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI07',
              parser_name: 'Velferdsetaten',
              name: 'Vest politidistrikt',
              email: 'post.vest@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 25,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI08',
              parser_name: 'Velferdsetaten',
              name: 'Møre og Romsdal politidistrikt',
              email: 'post.moreogromsdal@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 26,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI09',
              parser_name: 'Velferdsetaten',
              name: 'Trøndelag politidistrikt',
              email: 'post.trondelag@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 27,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI10',
              parser_name: 'Velferdsetaten',
              name: 'Nordland politidistrikt',
              email: 'post.nordland@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 28,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI11',
              parser_name: 'Velferdsetaten',
              name: 'Troms politidistrikt',
              email: 'post.troms@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 29,
              project_id: 6,
              list_id: 105,
              source_system: 'PDI12',
              parser_name: 'Velferdsetaten',
              name: 'Finnmark politidistrikt',
              email: 'post.finnmark@politiet.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 104,
              project_id: 12,
              list_id: 109,
              source_system: 'HSO',
              parser_name: 'HSO',
              name: 'Helse Sørøst RHF',
              email: 'postmottak@helse-sorost.no',
              description: '',
              registered_date: '2016-09-09',
              is_visible: true,
            },
            {
              id: 145,
              project_id: 12,
              list_id: 109,
              source_system: 'HVE',
              parser_name: 'BydelSagene',
              name: 'Helse Vest RHF',
              email: 'helse@helse-vest.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 144,
              project_id: 12,
              list_id: 109,
              source_system: 'HNO',
              parser_name: 'BydelSagene',
              name: 'Helse Nord RHF',
              email: 'postmottak@helse-nord.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 146,
              project_id: 12,
              list_id: 109,
              source_system: 'HMN',
              parser_name: 'BydelSagene',
              name: 'Helse Midt-Norge RHF',
              email: 'postmottak@helse-midt.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 125,
              project_id: 12,
              list_id: 109,
              source_system: 'AHUS',
              parser_name: 'HSO',
              name: 'Akershus Universitetssykehus HF',
              email: 'postmottak@ahus.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 126,
              project_id: 12,
              list_id: 109,
              source_system: 'SUN',
              parser_name: 'HSO',
              name: 'Sunnaas sykehus HF',
              email: 'firmapost@sunnaas.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 127,
              project_id: 12,
              list_id: 109,
              source_system: 'SIV',
              parser_name: 'HSO',
              name: 'Sykehuset i Vestfold HF',
              email: 'post@siv.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 128,
              project_id: 12,
              list_id: 109,
              source_system: 'SIN',
              parser_name: 'HSO',
              name: 'Sykehuset innlandet HF',
              email: 'postmottak@sykehuset-innlandet.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 133,
              project_id: 12,
              list_id: 109,
              source_system: 'STHF',
              parser_name: 'HSO',
              name: 'Sykehuset Telemark HF',
              email: 'postmottak@sthf.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 124,
              project_id: 12,
              list_id: 109,
              source_system: 'SOHF',
              parser_name: 'HSO',
              name: 'Sykehuset Østfold HF',
              email: 'postmottak@so-hf.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 129,
              project_id: 12,
              list_id: 109,
              source_system: 'VVHF',
              parser_name: 'HSO',
              name: 'Vestre Viken HF',
              email: 'postmottak@vestreviken.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 130,
              project_id: 12,
              list_id: 109,
              source_system: 'SPHF',
              parser_name: 'SSHF',
              name: 'Sykehuspartner HF',
              email: 'post@sykehuspartner.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 136,
              project_id: 12,
              list_id: 109,
              source_system: 'HSHF',
              parser_name: 'BydelSagene',
              name: 'Helgelandssykehuset HF',
              email: 'postmottak@helgelandssykehuset.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 131,
              project_id: 12,
              list_id: 109,
              source_system: 'FIHF',
              parser_name: 'BydelSagene',
              name: 'Finmarkssykehuset HF',
              email: 'postmottak@finnmarkssykehuset.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 137,
              project_id: 12,
              list_id: 109,
              source_system: 'NLSH',
              parser_name: 'BydelSagene',
              name: 'Nordlandssykehuset HF',
              email: 'postmottak@nordlandssykehuset.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 138,
              project_id: 12,
              list_id: 109,
              source_system: 'UNN',
              parser_name: 'BydelSagene',
              name: 'Universitetssykehuset Nord-Norge HF',
              email: 'post@unn.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 132,
              project_id: 12,
              list_id: 109,
              source_system: 'HMR',
              parser_name: 'BydelSagene',
              name: 'Helse Møre og Romsdal HF',
              email: 'postmottak@helse-mr.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 142,
              project_id: 12,
              list_id: 109,
              source_system: 'STO',
              parser_name: 'StOlavsHospital',
              name: 'St. Olavs Hospital HF',
              email: 'post@stolav.no',
              description: '',
              registered_date: '2017-09-14',
              is_visible: true,
            },
            {
              id: 135,
              project_id: 12,
              list_id: 109,
              source_system: 'HNT',
              parser_name: 'BydelSagene',
              name: 'Helse Nord-Trøndelag HF',
              email: 'postmottak@hnt.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 139,
              project_id: 12,
              list_id: 109,
              source_system: 'SUS',
              parser_name: 'BydelSagene',
              name: 'Helse Stavanger HF',
              email: 'post@sus.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 134,
              project_id: 12,
              list_id: 109,
              source_system: 'HFHF',
              parser_name: 'BydelSagene',
              name: 'Helse Fonna HF',
              email: 'post@helse-fonna.no',
              description: '',
              registered_date: '2017-09-12',
              is_visible: true,
            },
            {
              id: 141,
              project_id: 12,
              list_id: 109,
              source_system: 'HBHF',
              parser_name: 'BydelSagene',
              name: 'Helse Bergen HF',
              email: 'postmottak@helse-bergen.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 140,
              project_id: 12,
              list_id: 109,
              source_system: 'HFOE',
              parser_name: 'BydelSagene',
              name: 'Helse Førde HF',
              email: 'post@helse-forde.no',
              description: '',
              registered_date: '2017-09-13',
              is_visible: true,
            },
            {
              id: 147,
              project_id: 13,
              list_id: 111,
              source_system: 'Mattilsynet',
              parser_name: 'Mattilsynet',
              name: 'Mattilsynet',
              email: 'innsynshenvendelser@mattilsynet.no',
              description: '',
              registered_date: '2017-11-01',
              is_visible: true,
            },
          ]),
        ),
    );
};
